# See more at https://alacritty.org/config-alacritty.html

[general]
import = ["themes/vscode.toml"]

[window]
opacity = 0.95
blur = true

[window.dimensions]
columns = 120
lines = 40

[window.padding]
x = 16
y = 16

[font]
size = 12

[font.normal]
family = "MesloLGS NF"

[cursor.style]
blinking = "On"
shape = "Underline"

[terminal]
shell = "/bin/fish"
