[[alacritty]]
platform = "linux"
source = "alacritty/alacritty.linux.toml"
target = "~/.config/alacritty/alacritty.toml"

[[alacritty]]
platform = "mac"
source = "alacritty/alacritty.mac.toml"
target = "~/.config/alacritty/alacritty.toml"

[[alacritty]]
source = "alacritty/themes/"
target = "~/.config/alacritty/themes/"

[[cs2]]
source = "cs2/autoexec.cfg"

[[cs2]]
source = "cs2/lib/"

[[fish]]
source = "fish/config.fish"
target = "~/.config/fish/config.fish"

[[git]]
source = "git/config"
target = "~/.config/git/config"

[[git]]
source = "git/ignore"
target = "~/.config/git/ignore"

[[helix]]
source = "helix/config.root.toml"
target = "/root/.config/helix/config.toml"

[[helix]]
source = "helix/config.toml"
target = "~/.config/helix/config.toml"

[[helix]]
source = "helix/languages.toml"
target = "~/.config/helix/languages.toml"

[[starship]]
source = "starship/starship.toml"
target = "~/.config/starship.toml"
